/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;
import javax.swing.*;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.JDialog;

/**
 *
 * @author brotsky
 */
public class PAMHome extends javax.swing.JFrame {
    Vector data;
    Vector dataLine;
    Vector columns;

    /**
     * Creates new form PAMHome
     */
    public PAMHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonLogEvent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Activity", "Duration", "Date"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("PAM");

        buttonLogEvent.setText("Log Event");
        buttonLogEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(buttonLogEvent))
                .addGap(0, 170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLogEvent)))
                .addGap(0, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogEventActionPerformed
        // TODO add your handling code here:
        
        LogEventView logEvent = new LogEventView(this, true);
        logEvent.setVisible(true);
        
        
        String line;
        data = new Vector();
        dataLine = new Vector();
        columns = new Vector();
        
        columns.addElement("Activity");
        columns.addElement("Duration");
        columns.addElement("Date");
        
        try {
            
            BufferedReader br = new BufferedReader(new FileReader("src/PAMDB.txt"));            
            StringBuilder sb = new StringBuilder();
            //String st1 = br.readLine();
       //         StringTokenizer st1 = new StringTokenizer(br.readLine(), ",");
                while ((line = br.readLine()) != null) {
                        StringTokenizer st2 = new StringTokenizer(line, ",");
                        
                        String time = new String(st2.nextToken());
                        String activity = new String(st2.nextToken());
                        
                        //the second .nextToken() is causing issues
                        
                       // String duration = new String(st2.nextToken());
                        
                        dataLine.addElement(activity);
                        dataLine.addElement("duration");
                        dataLine.addElement(time);
                        
                        data.addElement(dataLine);
                }
                System.out.println(data);
                br.close();
        } catch (Exception e) {
                e.printStackTrace();
        }
        
table.setModel(new javax.swing.table.DefaultTableModel(
        data,
        columns));

     jScrollPane1.setViewportView(table);
        
        
        
        
        
        
        
//        try {
//            BufferedReader br = new BufferedReader(new FileReader("src/PAMDB.txt"));
//            
//            StringBuilder sb = new StringBuilder();
//            String line = br.readLine();
//
//            while (line != null) {
//                sb.append(line);
//                sb.append(System.lineSeparator());
//                line = br.readLine();
//                System.out.println(line);
//                
//            }
//            String everything = sb.toString();
//            br.close();
//        } catch(IOException ioe) {
//            
//        }
       
        
//        try {
//            FileReader fReader = new FileReader("src/PAMDB.txt");
//            BufferedReader inFile = new BufferedReader(fReader);
//            String input = inFile.readLine();
//            String[] valuesForLine;
//            Object[] dataSource = null;
//
//            
//            
//            while(input!=null) {
//                valuesForLine = input.split(",");
//                int x=0;
//                String[] row = null;
//                for(int i=0; i<valuesForLine.length;i++) {
//                    System.out.println(valuesForLine);
//                    dataSource[x]= valuesForLine[i]; 
//                    
//                }
////                dataSource[x] = row;
////                        x++;
//            }
//            table.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//            
//            dataSource,
//            
//        },
//        new String [] {
//            "Activity", "Date", "Duration"
//        }));
//            
//        }
//        catch(IOException ioe){            
//        }
            
//            while(input!=null) {
//                int x=0;		
//                temp = input.split(",",2);
//                for(int i=0;i<temp.length;i++){		
//                    System.out.println(temp[i]);	
//                }		
//                System.out.println("---------End of Line");		
//                input = inFile.readLine();
//            }
//        }catch(IOException ioe){
//            System.out.println("ERROR");
//        }
//	//endOfStringSplit
//	
//        Object rowData[][] = {
//    	/*
//		{ "1-1", "1-2", "1-3","1-4","1-5" },
//        { "2-1", "2-2", "2-3","2-4","2-5" } 
//    	*/
//        };
//        Object columnNames[] = { "Student Number", "Name", "Sex","College","Username","Password" };
        
        
        
//        try {
//            FileReader fReader = new FileReader("src/PAMDB.txt");
//            BufferedReader inFile = new BufferedReader(fReader);
//            String input = inFile.readLine();
//            Object test = input;
//            table.setModel(new javax.swing.table.DefaultTableModel(
//            test[][];
//            );
//        }catch(IOException ioe){            
//            }
            
//        table.setModel(new javax.swing.table.DefaultTableModel(
//        new Object [][] {
//            
//            
//            
//            {"Running", "09/05/14", "3", "0:45"},
//            {"Climbing", "09/07/14", "2", "0:22"},
//            {"Swimming", "09/11/14", "4", "1:15"},
//            {"Running", "09/05/14", "3", "0:45"},
//            {"Climbing", "09/07/14", "2", "0:22"},
//            {"Swimming", "09/11/14", "4", "1:15"},
//            {"Running", "09/05/14", "3", "0:45"},
//            {"Climbing", "09/07/14", "2", "0:22"},
//            {"Swimming", "09/11/14", "4", "1:15"},
//            {null, null, null, null}
//        },
//        new String [] {
//            "Activity", "Date", "Week", "Duration"
//        }));
//
//     jScrollPane1.setViewportView(table);
        


    }//GEN-LAST:event_buttonLogEventActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAMHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAMHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAMHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAMHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAMHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogEvent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}